### ISSUE TITLE
GPIO Zero

### ISSUE THREAD

**Issue by bennuttall** [andreipradan/raspberrypi-py#1]
Hi

I noticed you've started this library - it seems very similar to a project I launched recently and wanted to let you know in case you hadn't seen it. Perhaps you could contribute to it instead of duplicating the effort here? Check it out: http://gpiozero.readthedocs.org/

GPIO Zero is installed by default in Raspbian Jessie and endorsed by the Foundation.

**Comment by andreipradan** [comment]
Sure,
I'll see what I can do.
Thanks!

**Comment by andreipradan** [comment]
@bennuttall i've cloned your github repo and at a first glance it seems like your library is more focused on the low-level usage of gpio components, and this one is focused(besides the common led on led off functionality) on the high level usage of leds and buttons like LED light-games: making a group of lights behave in a certain way, like turning on or off one-by-one, pulsing and other behaviours like this. Maybe even creating a christmas-lights configuration.
It's main purpose though is for personal use and i'm not sure if i have the time to adapt it to gpiozero.
Maybe if I'll have some spare time I will use your library as a dependency, if I can easily plug it in here so that I can use functionalities like led on, led off, press button a.s.o.
If you have any ideas or advice on this approach, let me know.
Thanks!
